### ISSUE TITLE
When no `-x` argument (`options[:extension_keys]`) provided, fail safe

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/metanorma#12]
Don't crash, right now it gives error at:

`/lib/ruby/gems/2.4.0/gems/metanorma-0.2.2/exe/metanorma:132`

**Comment by opoudjis** [comment]
I cannot replicate this, at all. metanorma -t iso rice.adoc works fine. But clearly the gem had been updated since then, so I'm pushing a new version.
