### ISSUE TITLE
Update installation steps for Ubuntu

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/metanorma#17]
From our good friend @mjosaarinen :

>  I took a clean Ubuntu 18.04 image and installed that on
vmware to test out what the full list of dependencies is. ...
Some of that is not 100% trivial so you may want to use
that somewhere else too.

```sh
sudo apt install git make ruby-bundler ruby-dev libxml2-dev
libxslt-dev default-jre
sudo gem install bundler
sudo gem install nokogiri -v '1.8.4'
```

**Comment by opoudjis** [comment]
I think this is beyond my capability. Need to discuss.

**Comment by ronaldtse** [comment]
This task is just to add to documentation on how to setup Metanorma on Ubuntu.

Setup docker through dinghy on macOS:

```
brew tap codekitchen/dinghy
brew install dinghy
brew install docker docker-machine
dinghy create --provider virtualbox
```

Run the Ubuntu container:

```
dinghy up
eval $(dinghy env)
docker run -it ubuntu:18.10 bash
```

Setup prerequisites In the container:

```
apt-get update
apt install -y git make ruby-bundler ruby-dev libxml2-dev libxslt-dev default-jre
gem install metanorma
```

Metanorma is setup!

**Comment by opoudjis** [comment]
So, I'm adding these commands to the script in https://github.com/riboseinc/metanorma-macos-setup ? And  then adding documentation about this step in the Readme?

Surely this is an optional step, so we should add a command line argument in the script on whether to do a virtual Ubuntu?

**Comment by ronaldtse** [comment]
Let’s just put the Ubuntu instructions in the Metanorma README. The macOS script is really just macOS only.
