### ISSUE TITLE
Only allow backend selection when the backend type is installed

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/metanorma#2]
Just like how `asciidoctor` works -- we shouldn't allow using a backend that is not yet installed.

Right now it requires all the different types of backends to be installed to work.

**Comment by opoudjis** [comment]
I do not understand. Do you mean that the script should abort if the required gem is not installed? But why would we not simply import all required gems? It's not like importing four gems is unusual by gem standards?

**Comment by ronaldtse** [comment]
Not abort, but only allow entering if the backend is installed. An ISO author may never want to create a CSD document, vice versa.

The easy way to do it is:

```ruby
%w(mybackend1 mybackend2).each do |backend|
  begin
    require "metanorma/#{backend}"
  rescue LoadError
    puts "backend #{backend} not present"
  end
end
```

**Comment by ronaldtse** [comment]
Done in 6fa52a1.
