### ISSUE TITLE
HTML renderer ability to inline images into resulting HTML

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/metanorma#24]
In a Metanorma document that contain images, HTML distribution is hampered by the need of including the original location of images.

This task is to allow the base form of the Metanorma HTML renderer to allow "inlining" (i.e. data64) of images into the resulting HTML file for easier distribution.

**Comment by opoudjis** [comment]
I've thought about this for a while, but is it practical in all cases? Isn't there a size limit beyond which data64 encoding is not practical? https://github.com/riboseinc/metanorma-cli/issues/2 is also meant to address this concern by creating folders instead.

**Comment by opoudjis** [comment]
The option for isodoc shall be `data-uri-image`. Asciidoctor shall have the same option. The option will be passed to metanorma-cli as `-d` for --data-uri-image`.

**Comment by ronaldtse** [comment]
Agree for being "optional". Do we need `data-uri-image` or just `data-uri` suffices? (since there won't be audio/video...)

**Comment by opoudjis** [comment]
Done in metanorma-cli, metanorma-standoc, isodoc, metanorma

**Comment by opoudjis** [comment]
We don't know that there won't  be video or audio in customisations of the toolset, and if there will be, their data URIs could be unworkably big. Rather keep label as is.

**Comment by ronaldtse** [comment]
OK
