### ISSUE TITLE
Wrong file lookup path for --type csd

### ISSUE THREAD

**Issue by CAMOBAP795** [riboseinc/metanorma#37]
When we run `metanorma` with `--type csd` outside directory where adoc file placed, tried to lookup files in wrong path

Initially found here https://github.com/riboseinc/homebrew-metanorma/pull/2#issuecomment-455129746

**Comment by opoudjis** [comment]
I cannot replicate on Mac, but I *think* I know what the fix is; it's the fix I've just had to do for image processing in outside directories: https://github.com/riboseinc/metanorma-nist/issues/38

**Comment by opoudjis** [comment]
Replicated (it's the absolute path that triggers it, not a relative path).

**Comment by opoudjis** [comment]
Issue is in metanorma gem: it is assuming the URL of the PDF HTML document is relative, which is incorrect.

**Comment by opoudjis** [comment]
Fixed in metanorma gem.
