### ISSUE TITLE
Request: Metanorma M3AAWG documents

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/metanorma#4]
We just received a request from CalConnect's TC CALSPAM to make Metanorma work with M3AAWG documents too.

Here's a sample of how theirs look like, they use PDF.
https://www.m3aawg.org/sites/default/files/m3aawg-senders-complaint-handling-2017-12.pdf

I think we can do a M3AAWG branded HTML styling and a PDF output via HTML Print or Word?

cc: @opoudjis

**Comment by ronaldtse** [comment]
We're calling this format M3D (M3AAWG Document)

* Models: https://github.com/riboseinc/m3d-models
* Styling: https://github.com/riboseinc/m3d-styles
* AsciiDoctor backend: https://github.com/riboseinc/asciidoctor-m3d

**Comment by opoudjis** [comment]
PDF output: recall that we could only autogenerate PDF from Word via an inaccessible libreoffice addin. If the PDF can be completely generated from HTML, we don't need a Word version. But the PDF sample is clearly Word-generated: it has a footer, page numbers, table of contents with page numbers,  and a colophon.

Btw, we have no provided for colophons in documents to date. This will be a change to Isodoc, with an additional section and template file.

**Comment by ronaldtse** [comment]
For PDF there are only two ways here, either we go through third-party software or use the Ruby `prawn` gem which is used by `asciidoctor-pdf`. Currently it should be enough creating a Word doc which the user can PDF themselves.

**Comment by opoudjis** [comment]
I'm closing this ticket, since the work has been done in the asciidoctor-m3d gem.

We have a working HTML to PDF solution now in CSD; but HTML deals poorly with page numbers (particularly table of content page numbers), so for M3AAWG we will stick with Word.
