### ISSUE TITLE
Allow selection of output format

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/metanorma#5]
Most metanorma modules generate multiple output formats in addition to their own XML:

* asciidoctor-csd : CSDXML, HTML and PDF
* asciidoctor-rfc: XMLRFC
* asciidoctor-iso: ISOXML, HTML and Word DOC
* asciidoctor-m3d: M3DXML and Word DOC
* asciidoctor-csand: CSANDXML, HTML and PDF

The user should be able to select these formats via a command line argument, such as:

```sh
metanorma -t csd --output mydoc.csd.xml --output-html mydoc.html --output-pdf mydoc.pdf mydoc.adoc
```
(something like this)

**Comment by ronaldtse** [comment]
Related to https://github.com/riboseinc/asciidoctor-iso/issues/94#issuecomment-396753159

**Comment by opoudjis** [comment]
"can we have a command flag that allows outputting Metanorma XML to disk?"
